pipeline.yml
name: Artifacts
on: 
    push:
       branches:["main"]
       jobs:
        build:
          runs-on: ubuntu-latest
          steps:
             name: Checkout
              run: touch hellow.txt